### ISSUE TITLE
Refactor frontend with React

### ISSUE THREAD

**Issue by VVatashi** [lewd-site/backend#93]
- [x] Use redux for hotkeys.
- [x] Use redux for settings.
- [ ] Use redux for posts.
- [x] Use react for hotkeys settings section.
- [x] Refactor settings popup.
- [x] Refactor tools widget.
- [x] Refactor style selector.
- [ ] Refactor posting form.
- [ ] Refactor login/register forms.
- [ ] Refactor media modal.
- [ ] Refactor post popup.
- [ ] Refactor admin dashboard.
- [ ] Refactor board view.
- [ ] Refactor thread view.

**Comment by UserNaem** [comment]
If you intend on ~~breaking~~ refactoring everything again, keep it in a separate branch, the master branch had more than enough issues as it is.

**Comment by VVatashi** [comment]
@UserNaem, there are no new reported bugs recently. Create an issue if you found any.
Requests for new features (including porting of the missing functionality of the DE, etc) will be much easier to complete after refactoring.

**Comment by UserNaem** [comment]
Should I also report issues neither of us will live to see fixes for? Or issues that have already re-emerged on their own?

After that the stable branch's been revived and murdered multiple times, it's getting increasingly harder to keep track of all the new breakage; nocturnal.css definitely does not look the way it "should" (as I envision it), but no way to figure out what exactly is wrong with it now.

**Comment by VVatashi** [comment]
@UserNaem 
Гуми, если честно, ты за🙈бал писать по-английски. Всё равно, кроме нас, это обсуждение тут никому не нужно. (Не говоря уже о том, что мой английский всё ещё достаточно плох, и у меня просто нет на это времени)

Да, если тебе кажется, что что-то не так, ты можешь открыть исую. Рано или поздно я до них доберусь. Просто в данный момент добавление нового функционала в наименьшем приоритете, потому что, чтобы его сейчас без проблем добавлять, и не проделывать одну и ту же работу как минимум дважды, мне стоит весь фронт отрефакторить и привести к какому-то единому порядку. (Пока же там цирк с конями из разных технологий и велосипедов, опробованных мной за пару лет, не к моему оправданию...)

Да, для регрессий тоже стоит открывать исуи (переоткрывать существующие, если они есть). Иначе я могу о них просто не узнать, пока сама не столкнусь. (А у тебя обычно претензии к ошибкам, которые возникают при совершении совсем нетипичных действий, в необычном окружении и т.д., в частности из-за этого они могут быть незамеченными неопределённое время.)

Только, пожалуйста, не называй регрессиями отсутствующий функционал куклоскрипта и т.п. Определённая его версия была первое время встроена лишь для удобства и упрощения, но это всё же сторонний юзерскрипт, и неотъемлимой частью фронта он никогда не был. Если ты сравниваешь текущий функционал с функционалом бывшей когда-то стейбл-ветки, делай это с отключенным куклоскриптом. Иначе это вовсе не багрепорты, а реквесты нового функционала в чистом виде.

Nocturnal, на сколько мне известно, изначально был юзерстилем для 4chan. Собственно, в виде того самого юзерстиля я его тебе и рекомендую найти, если тебе кажется, что сейчас что-то не так, как было изначально в нём.
